List<String> drugNames = [
  'Acetaminophen',
  'Adderall',
  'Amitriptyline',
  'Amlodipine',
  'Amoxicillin',
  'Ativan',
  'Atorvastatin',
  'Azithromycin',
  'Benzonatate',
  'Brilinta',
  'Bunavail',
  'Buprenorphine',
  'Cephalexin',
  'Ciprofloxacin',
  'Citalopram',
  'Clindamycin',
  'Clonazepam',
  'Cyclobenzaprine',
  'Cymbalta',
  'Doxycycline',
  'Dupixent',
  'Entresto',
  'Entyvio',
  'Farxiga',
  'Fentanyl Patch',
  'Gabapentin',
  'Gilenya',
  'Humira',
  'Hydrochlorothiazide',
  'Hydroxychloroquine',
  'Ibuprofen',
  'Imbruvica',
  'Invokana',
  'Januvia',
  'Jardiance',
  'Kevzara',
  'Lexapro',
  'Lisinopril',
  'Lofexidine',
  'Loratadine',
  'Lyrica',
  'Melatonin',
  'Meloxicam',
  'Metformin',
  'Methadone',
  'Methotrexate',
  'Metoprolol',
  'Naloxone',
  'Naltrexone',
  'Naproxen',
  'Narcan',
  'Nurtec',
  'Omeprazole',
  'Onpattro',
  'Otezla',
  'Ozempic',
  'Pantoprazole',
  'Plan B',
  'Prednisone',
  'Probuphine',
  'Rybelsus',
  'secukinumab',
  'Sublocade',
  'Tramadol',
  'Trazodone',
  'Viagra',
  'Wegovy',
  'Wellbutrin',
  'Xanax',
  'Zubsolv',
  'Abilify',
  'Abilify Maintena',
  'Abiraterone',
  'Acetaminophen',
  'Acetylcysteine',
  'Actemra',
  'Actos',
  'Acyclovir',
  'Adderall',
  'Adderall XR',
  'Advair Diskus',
  'Advil',
  'Afinitor',
  'Aimovig',
  'Ajovy',
  'Albuterol',
  'Aldactone',
  'Alecensa',
  'Alendronate',
  'Aleve',
  'Allegra',
  'A/B Otic',
  'Abacavir',
  'Abacavir and lamivudine',
  'Abacavir and Lamivudine Tablets',
  'Abacavir Oral Solution',
  'Abacavir Sulfate Tablets',
  'Abacavir, dolutegravir, and lamivudine',
  'Abacavir, Lamivudine and Zidovudine Tablets',
  'Abacavir, lamivudine, and zidovudine',
  'Abaloparatide',
  'Abaloparatide Subcutaneous',
  'Abametapir Topical application',
  'Abatacept',
  'Abatacept Intravenous',
  'Abatuss DMX',
  'Abavite',
  'Abbokinase',
  'Abciximab',
  'Abciximab Intravenous',
  'Abecma',
  'Abelcet',
  'Abemaciclib',
  'Abenol',
  'Abilify',
  'Abilify Discmelt',
  'Abilify Intramuscular',
  'Abilify Maintena',
  'Abilify Mycite',
  'Abilify MyCite Maintenance Kit oral with sensor',
  'Abilify MyCite Starter Kit oral with sensor',
  'Abiraterone',
  'Abiraterone, micronized',
  'Ablavar',
  'Ablysinol',
  'AbobotulinumtoxinA',
  'Abobotulinumtoxina Intramuscular',
  'Abraxane',
  'Abreva',
  'Abreva Topical',
  'ABRILADA Subcutaneous',
  'Abrocitinib',
  'Absorbine Athletes Foot',
  'Absorbine Jr. Antifungal',
  'Absorbine Jr. Antifungal Topical',
  'Absorica',
  'Absorica LD',
  'Abstral',
  'Abstral Sublingual Tablet',
  'A-Caro-25',
  'Acacia Gum',
  'Acai',
  'Acalabrutinib',
  'ACAM2000',
  'Acamprosate',
  'Acanya',
  'Acarbose',
  'Acb',
  'Accel-clonazePAM',
  'Accelerated Covid-19 Test Kit',
  'AccessPak for HIV PEP Basic',
  'AccessPak for HIV PEP Expanded with Kaletra',
  'AccessPak for HIV PEP Expanded with Viracept',
  'Acclean',
  'Acclean 60 Second Fluoride Treatment',
  'Acclean Plus',
  'Accolate',
  'Accretropin',
  'Accrufer',
  'Accrufer Oral',
  'Accucaine',
  'Accuneb',
  'Accupril',
  'Accuretic',
  'Accutane',
  'ACD A',
  'ACD Blood Pack Units',
  'Acebutolol',
  'Acella Antipyrine and Benzocaine Otic Solution',
  'Aceon',
  'Acephen',
  'Acephen rectal',
  'Acerola',
  'Acetadote',
  'Acetaminophen',
  'Acetaminophen and benzhydrocodone',
  'Acetaminophen and butalbital',
  'Acetaminophen and caffeine',
  'Acetaminophen and chlorpheniramine',
  'Acetaminophen and codeine',
  'Acetaminophen and Codeine Oral Solution',
  'Acetaminophen and dextromethorphan',
  'Acetaminophen and diphenhydramine',
  'Acetaminophen and ibuprofen',
  'Acetaminophen and Oxycodone',
  'Acetaminophen and phenylephrine',
  'Acetaminophen and phenyltoloxamine',
  'Acetaminophen and pseudoephedrine',
  'Acetaminophen and tramadol',
  'Acetaminophen injection',
  'Acetaminophen Intravenous',
  'Acetaminophen Oral, Rectal',
  'Acetaminophen rectal',
  'Acetaminophen, aspirin, and caffeine',
  'Acetaminophen, butalbital, and caffeine',
  'Acetaminophen, butalbital, caffeine, and codeine',
  'Acetaminophen, caffeine, and dihydrocodeine',
  'Acetaminophen, caffeine, and magnesium salicylate',
  'Acetaminophen, chlorpheniramine, and dextromethorphan',
  'Acetaminophen, chlorpheniramine, and phenylephrine',
  'Acetaminophen, chlorpheniramine, dextromethorphan, and pseudoephedrine',
  'Acetaminophen, dextromethorphan, and diphenhydramine',
  'Acetaminophen, dextromethorphan, and doxylamine',
  'Acetaminophen, dextromethorphan, and phenylephrine',
  'Acetaminophen, dextromethorphan, and triprolidine',
  'Acetaminophen, dextromethorphan, doxylamine, and phenylephrine',
  'Acetaminophen, dextromethorphan, doxylamine, and pseudoephedrine',
  'Acetaminophen, dextromethorphan, guaifenesin, and phenylephrine',
  'Acetaminophen, dextromethorphan, guaifenesin, and pseudoephedrine',
  'Acetaminophen, dextromethorphan, phenylephrine, and triprolidine',
  'Acetaminophen, diphenhydramine, and phenylephrine',
  'Acetaminophen, magnesium salicylate, and pamabrom',
  'Acetaminophen, pamabrom, and pyrilamine',
  'Acetaminophen, pheniramine, and phenylephrine',
  'Acetasol HC',
  'Acetasol HC otic',
  'Acetazolamide',
  'Acetazolamide Capsules',
  'Acetazolamide Intravenous',
  'Acetazolamide Tablets',
  'Acetic Acid',
  'Acetic acid and hydrocortisone otic',
  'Acetic acid irrigant',
  'Acetic Acid Irrigation',
  'Acetic acid otic',
  'Acetic acid vaginal',
  'Acetohydroxamic acid',
  'Acetone, isopropyl alcohol, and polysorbate Topical',
  'Acetoxyl 10 Topical',
  'Acetoxyl 2.5 Topical',
  'Acetoxyl 20 Topical',
  'Acetoxyl 5 Topical',
  'Acetylcysteine',
  'Acetylcysteine inhalation',
  'Acetylcysteine Inhalation, oral/nebulization',
  'Acetylcysteine Injection',
  'Acetylcysteine Intravenous',
  'Acetylcysteine Solution',
  'Achromycin V',
  'Aci-Jel vaginal',
  'Acid Controller Original Strength',
  'Acid Gone',
  'Acid Gone Extra Strength',
  'Acid Jelly vaginal',
  'Acidic Vaginal Jelly vaginal',
  'Acidophilus',
  'Acilac',
  'Aciphex',
  'AcipHex Sprinkle',
  'Acitretin',
  'Acitretin Capsules',
  'Ackee',
  'Aclasta',
  'Aclidinium',
  'Aclidinium and formoterol',
  'Aclidinium and formoterol Inhalation',
  'Aclidinium Inhalation',
  'Aclovate',
  'Acne 10 Gel Topical,'
      'Acne Topical',
  'Acne Wash Topical',
  'Acne-Aid Gel Topical',
  'Acne-Clear',
  'Acnevir',
  'Acnex Topical',
  'Acnomel Acne Mask Topical',
  'Acnomel Bp 5 Topical',
  'Acnomel Skin Tone Topical',
  'Acnomel Vanishing Topical',
  'Acomplia',
  'Aconite',
  'Acrivastine and pseudoephedrine',
  'ACT Amphetamine XR - 10MG Tablet',
  'ACT Amphetamine XR - 15MG Tablet',
  'ACT Amphetamine XR - 20MG Tablet',
  'ACT Amphetamine XR - 25MG Tablet',
  'ACT Amphetamine XR - 30MG Tablet',
  'ACT Amphetamine XR - 5MG Tablet',
  'ACT COVID-19 Antibody Test',
  'ACT Fluoride Rinse',
  'ACT metFORMIN',
  'ACT Nabilone',
  'Act risperiDONE',
  'ACT-Escitalopram ODT',
  'ACT-traMADol/ACET',
  'Actamin',
  'Actamin Maximum Strength',
  'Actemra',
  'Actemra ACTPen',
  'Acthar Gel, H.P.',
  'ActHIB',
  'Acthrel',
  'Acticin',
  'Acticin Topical',
  'Acticlate',
  'Actidose',
  'Actidose-Aqua',
  'Actifed',
  'Actifed Cold & Allergy',
  'Actifed Sinus Regular',
  'Actigall',
  'Actimmune',
  'Actimol Children\'s',
  'Actimol Infant',
  'Actiprofen',
  'Actiq',
  'Actisite',
  'Activase',
  'Activated charcoal',
  'Activella',
  'Activella Oral',
  'ActivICE',
  'Actonel',
  'Actonel with Calcium',
  'Actoplus Met',
  'Actoplus Met XR',
  'Actos',
  'Acuflex',
  'Acular',
  'Acular LS',
  'Acular PF',
  'Acunistat-30 Injection System',
  'Acunistat-60 Injection System',
  'Acunivive 15 Injection System',
  'Acunivive 30 Injection System',
  'Acunivive 60 Injection System',
  'Acunivive 90 Injection System',
  'Acunol',
  'Acuvail',
  'Acuvue Theravision with Ketotifen',
  'Acyclovir',
  'Acyclovir (Systemic)',
  'Acyclovir and hydrocortisone topical',
  'Acyclovir and hydrocortisone Topical application',
  'Acyclovir Buccal mucosa',
  'Acyclovir Capsules',
  'Acyclovir Cream',
  'Acyclovir injection',
  'Acyclovir IV Infusion',
  'Acyclovir Ointment',
  'Acyclovir Ophthalmic',
  'Acyclovir Oral Suspension',
  'Acyclovir Oral, Intravenous',
  'Acyclovir Tablets',
  'Acyclovir topical',
  'Acys-5',
  'Aczone',
  'Aczone Topical',
  'Adacel',
  'Adacel Intramuscular',
  'Adacel Tdap',
  'Adagen',
  'Adagrasib',
  'Adakveo',
  'Adakveo Injection',
  'Adalat',
  'Adalat CC',
  'Adalat OROS',
  'Adalat PA 10',
  'Adalat PA 20',
  'Adalat XL',
  'Adalimumab',
  'Adalimumab Subcutaneous',
  'Adalimumab-aacf Subcutaneous',
  'Adalimumab-adaz Subcutaneous',
  'Adalimumab-adbm Subcutaneous',
  'Adalimumab-afzb Subcutaneous',
  'Adalimumab-aqvh Subcutaneous',
  'Adalimumab-atto Subcutaneous',
  'Adalimumab-bwwd Subcutaneous',
  'Adalimumab-fkjp Subcutaneous',
  'Adapalene',
  'Adapalene and Benzoyl Peroxide Gel',
  'Adapalene and benzoyl peroxide topical',
  'Adapalene and benzoyl peroxide Topical application',
  'Adapalene Cream',
  'Adapalene Solution',
  'Adapalene topical',
  'Adasuve',
  'Adbry',
  'Adcetris',
  'Adcirca',
  'Addamel N',
  'Addaprin',
  'Adderall',
  'Adderall XR',
  'Additive Formula 3',
  'Addyi',
  'Adefovir',
  'Adefovir Dipivoxil',
  'Adempas',
  'Adempas Tablets',
  'Adenocard',
  'Adenoscan',
  'Adenosine',
  'Adenosine Intravenous',
  'Adenovirus Type 4-and Type-7 Vaccine Live',
  'Adenovirus Vaccine',
  'Adenovirus vaccine, live',
  'Adhansia XR',
  'Adipex-P',
  'Adlarity',
  'Adlyxin',
  'Admelog',
  'Ado-trastuzumab emtansine',
  'Ado-trastuzumab emtansine Intravenous',
  'Adoxa CK',
  'Adoxa Pak',
  'Adoxa TT',
  'Adrenaclick',
  'Adrenalin',
  'Adrenalin Chloride',
  'Adrenalin Inhalation',
  'Adrenalin Injection',
  'AdreView',
  'Adriamycin',
  'Adrucil',
  'Adrucil injection',
  'Adsol Red Cell Preservation System',
  'Adstiladrin',
  'Adthyza',
  'Aducanumab',
  'Aducanumab-avwa Intravenous',
  'Aduhelm',
  'Adult Nighttime Cold/Flu Relief - Cherry Flavor',
  'Adult Nighttime Cold/Flu Relief - Original Flavor',
  'Advair',
  'Advair Diskus',
  'Advair Diskus 100/50',
  'Advair Diskus 250/50',
  'Advair Diskus 500/50',
  'Advair HFA',
  'Advair HFA 115/21',
  'Advair HFA 230/21',
  'Advair HFA 45/21',
  'Advair Inhalation Aerosol',
  'Advanced Eye Relief Dry Eye',
  'Advantage Multi for Dogs',
  'Advate',
  'Advicor',
  'Advil',
  'Advil Allergy Sinus',
  'Advil Children\'s',
  'Advil Childrens Allergy Sinus',
  'Advil Cold & Sinus',
  'Advil Cold and Sinus Liqui-Gel',
  'Advil Dual Action With Acetaminophen',
  'Advil Infants Concentrated Drops',
  'Advil Liqui-Gels',
  'Advil Migraine',
  'Advil Mini Gels',
  'Advil Multi-Symptom Cold',
  'Advil Pediatric',
  'Advil PM',
  'Advil PM Liqui-Gels',
  'Advil Sinus Congestion & Pain',
  'Adynovate',
  'Adynovate recombinant',
  'Adyphren',
  'Adyphren II',
  'Adzenys ER',
  'Adzenys ER Oral Suspension',
  'Adzenys XR-ODT',
  'Aemcolo',
  'Aerobid',
  'Aerobid-M',
  'Aerospan',
  'Afamelanotide',
  'Afamelanotide Subcutaneous',
  'Afatinib',
  'Afeditab CR',
  'Affodel',
  'Afinitor',
  'Afinitor Disperz',
  'Afirmelle',
  'Aflaxen',
  'Aflibercept',
  'Aflibercept Injection',
  'Aflibercept ophthalmic',
  'Afluria',
  'Afluria 2015-2016 Formula',
  'Afluria PF Pediatric Quadrivalent 2021-2022 injection',
  'Afluria PF Quadrivalent 2021-2022 injection',
  'Afluria Quadrivalent',
  'Afluria Quadrivalent 2021-2022 injection',
  'Afrezza',
  'African Basil',
  'African Mango',
  'Afrin',
  'Afrin 4 Hour Extra Moisturizing',
  'Afrin No Drip Sinus',
  'Afrin Saline nasal',
  'Afstyla',
  'Afstyla recombinant',
  'Aftate Topical',
  'AfterPill',
  'A-G Profen',
  'AG-ACET-traMADol',
  'AG-metFORMIN - Blackberry',
  'AG-metFORMIN - Unflavored',
  'AG-risperiDONE',
  'Agalsidase beta',
  'Agalsidase beta Intravenous',
  'Aggrastat',
  'Aggrenox',
  'AgonEaze',
  'Agriflu',
  'Agrimony',
  'Agrylin',
  'A-Hydrocort',
  'AH-Chew II',
  'AHCC',
  'Aimovig',
  'Aimovig SureClick Autoinjector',
  'Air',
  'Air Compressed',
  'AirDuo Digihaler',
  'AirDuo Digihaler with eModule',
  'AirDuo RespiClick',
  'Airsupra',
  'Airsupra inhalation',
  'Aivlosin',
  'Ajovy',
  'Ajovy Injection',
  'Ak-Chlor',
  'AK-Con',
  'AK-Dilate',
  'AK-Dilate Ophthalmic',
  'AK-Fluor',
  'AK-NaCl',
  'AK-Pentolate Ophthalmic',
  'AK-Poly-Bac',
  'AK-Pred',
  'AK-Taine',
  'Akineton',
  'Aklief',
  'Aklief Cream',
  'Akne-mycin Ointment',
  'Akne-Mycin Topical',
  'Akovaz',
  'Akten',
  'Akten Gel',
  'Aktipak',
  'AKTob',
  'Akurza Topical',
  'Akwa Tears',
  'Akynzeo',
  'Akynzeo for injection',
  'Akynzeo Intravenous',
  'Ala Hist IR',
  'Ala Hist PE',
  'Ala Quin Cream',
  'Ala Scalp',
  'Ala-Cort',
  'Ala-Cort Cream',
  'Ala-Hist AC',
  'Ala-Hist DHC',
  'Ala-Scalp HP',
  'Ala-Scalp Lotion',
  'Ala-Tet',
  'Alahist CF',
  'Alahist D',
  'Alahist DM',
  'Alamast',
  'Alavert',
  'Alavert D-12',
  'Alavert D-12 Hour Allergy and Sinus',
  'Alavert-D 12-Hour',
  'Alavert-D 12-Hour Oral',
  'Alaway',
  'Albalon',
  'Albendazole',
  'Albenza',
  'Albiglutide Subcutaneous',
  'Albuked',
  'Albuked 25',
  'Albuked 5',
  'Albuked human',
  'Albumarc',
  'Albumin (Human) 20%',
  'Albumin human',
  'Albumin human Intravenous',
  'Albuminar',
  'Albuminar-25',
  'Albuminar-25 human',
  'Albuminex Injection',
  'Alburx',
  'Alburx human',
  'Albutein',
  'Albutein 25%',
  'Albutein 5%',
  'Albutein human',
  'Albuterol',
  'Albuterol Aerosol',
  'Albuterol and budesonide inhalation',
  'Albuterol and ipratropium inhalation',
  'Albuterol Extended-Release Tablets',
  'Albuterol Inhalation',
  'Albuterol Inhalation Solution',
  'Albuterol Oral Solution',
  'Albuterol Syrup',
  'Alcaftadine',
  'Alcaftadine ophthalmic',
  'Alcaine',
  'Alclometasone',
  'Alclometasone Ointment',
  'Alclometasone topical',
  'Alcohol',
  'Alcohol and Dextrose',
  'Alcohol in Dextrose',
  'Alcon Tears',
  'Alcortin A Gel',
  'Alcortin A topical',
  'Aldactazide',
  'Aldactone',
  'Aldara',
  'Aldara Topical',
  'Aldesleukin',
  'Aldesleukin Intravenous',
  'Aldex D',
  'Aldex G',
  'Aldomet',
  'Aldoril',
  'Aldurazyme',
  'Alecensa',
  'Alectinib',
  'Alefacept Intramuscular',
  'Alemtuzumab',
  'Alemtuzumab Intravenous',
  'Alendronate',
  'Alendronate and cholecalciferol',
  'Alendronate Oral Solution',
  'Alera',
  'Alert',
  'Alesse',
  'Alesse Oral',
  'Alesse-28 Oral',
  'Aletris',
  'Aleve',
  'Aleve Arthritis',
  'Aleve Cold and Sinus',
  'Aleve PM',
  'Aleve Sinus & Headache',
  'Aleve-D Sinus & Cold',
  'Alfalfa',
  'Alfentanil',
  'Alfentanil Intravenous',
  'Alferon N',
  'Alfuzosin',
  'Alfuzosin Tablets',
  'Alglucerase Intravenous',
  'Alglucosidase Alfa',
  'Alglucosidase alfa injection',
  'Alglucosidase alfa Intravenous',
  'Aliclen Topical',
  'Alimta',
  'Alinia',
  'Aliqopa',
  'Alirocumab',
  'Alirocumab Subcutaneous',
  'Aliskiren',
  'Aliskiren and amlodipine',
  'Aliskiren and hydrochlorothiazide',
  'Aliskiren Tablets',
  'Aliskiren, amlodipine, and hydrochlorothiazide',
  'Alitretinoin',
  'Alitretinoin topical',
  'Alivio',
  'Alka-Seltzer',
  'Alka-Seltzer Anti-Gas',
  'Alka-Seltzer Cold and Sinus',
  'Alka-Seltzer Morning Relief',
  'Alka-Seltzer Plus Cold',
  'Alka-Seltzer Plus Cold and Cough',
  'Alka-Seltzer Plus Cold and Sinus',
  'Alka-Seltzer Plus Cold Formula',
  'Alka-Seltzer Plus Night-Time Cold',
  'Alkanna Root',
  'Alkeran',
  'Alkeran IV',
  'Alkeran Tablets',
  'Alkindi Sprinkle',
  'All Day Allergy-D',
  'All Day Pain Relief',
  'All Day Relief',
  'All-Nite',
  'Allan Tannate Pediatric',
  'Allanhist PDX Drops',
  'Allantoin, camphor, and phenol topical',
  'AllanVan-S',
  'Allegra',
  'Allegra 12 Hour Allergy',
  'Allegra 24 Hour Allergy',
  'Allegra Allergy',
  'Allegra ODT',
  'Allegra Oral',
  'Allegra OTC',
  'Allegra-D',
  'Allegra-D 12 hour',
  'Allegra-D 24 Hour',
  'Allegra-D Oral',
  'Aller-Chlor',
  'Aller-Ease',
  'AllerDur',
  'Allerest 12 Hour Nasal Spray',
  'Allerest Maximum Strength',
  'Allerest No Drowsiness',
  'Allerest PE',
  'Allergenic Extract, Bee and Wasp',
  'Allergenic Extract, Coca Glycerine',
  'Allergenic Extract, Standardized Mites',
  'Allergenic Extracts Injection',
  'Allergenic Extracts, Grass',
  'Allergenic Extracts, Grass Pollen',
  'Allergy & Congestion Relief',
  'Allergy Relief',
  'Allergy Relief (Fexofenadine HCl)',
  'Allergy Relief D',
  'Allergy Sinus Medication Extra Strength',
  'Allermax',
  'AllerNaze',
  'Allersol',
  'Allerx-D',
  'Allfen',
  'Allfen C',
  'Allfen CD',
  'Allfen CX',
  'Alli',
  'AlloPAX',
  'Allopurinol',
  'Allopurinol Injection',
  'Allopurinol Intravenous',
  'Allres PD',
  'Allspice',
  'Allzital',
  'Almacone',
  'Almond/Almond Oil',
  'Almora',
  'Almotriptan',
  'Alocril',
  'Alodox',
  'Aloe',
  'Aloe Grande topical',
  'Aloe polysaccharides, hydrocortisone, and iodoquinol topical',
  'Aloe vera topical',
  'Aloe Vesta 2-N-1 Antifungal Topical',
  'Aloe Vesta Antifungal Topical',
  'Alogliptin',
  'Alogliptin and metformin',
  'Alogliptin and Metformin Tablets',
  'Alogliptin and pioglitazone',
  'Alogliptin and Pioglitazone Tablets',
  'Alomide',
  'Aloprim',
  'Aloquin Gel',
  'Alora',
  'Alora skin patch',
  'Alora Transdermal',
  'losetron',
  'Aloxi',
  'Aloxi Capsules',
  'Alpelisib',
  'Alpha 1-proteinase inhibitor',
  'Alpha Lipoic Acid',
  'Alpha-1 proteinase inhibitor human Intravenous',
  'Alpha-E',
  'Alpha-Lac',
  'Alpha-Pro Gel',
  'Alphagan P',
  'Alphanate',
  'Alphanine SD',
  'Alphatrex',
  'Alprazolam',
  'Alprazolam Extended Release',
  'Alprazolam Intensol',
  'Alprazolam ODT',
  'Alprazolam Oral',
  'Alprazolam XR',
  'Alprolix',
  'Alprolix Intravenous',
  'Alprolix Intravenous, Injection',
  'Alprostadil',
  'Alprostadil injectable and transurethral',
  'Alprostadil Intraurethral, Intravenous, Intracavernosal',
  'Alprostadil Intravenous',
  'Alprostadil Urethral',
  'Alquam-X Acne Therapy Gel Topical',
  'Alrex',
  'Alrex ophthalmic',
  'Alsuma',
  'Altabax',
  'Altacaine',
  'Altacaine Ophthalmic Solution',
  'Altace',
  'Altachlore ophthalmic',
  'Altaflor',
  'Altafluor',
  'Altafrin',
  'Altafrin Ophthalmic',
  'Altamist nasal',
  'Altarussin',
  'Altarussin CF',
  'Altavera',
  'Altazine',
  'Altenol',
  'Alteplase',
  'Alteplase, recombinant Intravenous',
  'Alti-Alprazolam Oral',
  'Alti-Amoxi Clav',
  'Alti-Haloperidol',
  'Alti-Ipratropium',
  'Alti-Ipratropium With Preservative',
  'Alti-Mpa',
  'Alti-Mpa Oral',
  'Alti-Nadolol',
  'Alti-Orciprenaline',
  'Alti-Pindolol',
  'Alti-Piroxicam',
  'Alti-Salbutamol Inhalation Aerosol',
  'Alti-sulfaSALAzine',
  'Alti-Valproic',
  'Altocor',
  'Altoprev',
  'Altreno',
  'Altreno Topical',
  'Altretamine',
  'Altuviiio',
  'Altuviiio Intravenous',
  'Aluminum Acetate',
  'Aluminum Chloride (Topical)',
  'Aluminum chloride hexahydrate topical',
  'Aluminum hydroxide',
  'Aluminum hydroxide and magnesium carbonate',
  'Aluminum hydroxide and magnesium trisilicate',
  'Aluminum hydroxide, magnesium hydroxide, and simethicone',
  'Alunbrig',
  'Alupent',
  'Alupent Inhalation',
  'Aluvea',
  'Alvesco',
  'Alvesco HFA inhalation',
  'Alvimopan',
  'Alyacen 7/7/7',
  'Alyacen 1/35',
  'Alymsys',
  'Alymsys Intravenous',
  'Alyq',
  'A-Methapred',
  'A-Methapred injection',
  'Amabelz',
  'Amantadine',
  'Amantadine Oral Solution USP',
  'Amantadine Syrup',
  'antadine Tablets',
  'Amaryl',
  'Amazonian Basil',
  'Ambator Diclofenac Patch',
  'Ambator Lidocaine Patch',
  'Ambien',
  'Ambien CR',
  'Ambien CR Oral',
  'Ambien Oral',
  'Ambifed CD',
  'Ambifed-G',
  'Ambisome',
  'Ambrisentan',
  'Ambrisentan Tablets',
  'Ambroxol',
  'Amcinonide',
  'Amcinonide Lotion',
  'Amcinonide topical',
  'Amcinonide Topical application',
  'Ameluz Gel',
  'Ameluz topical',
  'Amerge',
  'Amethia',
  'Amethia extended-cycle',
  'Amethia Lo',
  'Amethia Lo extended-cycle',
  'Amethyst',
  'Amevive',
  'Amevive Intramuscular',
  'Amibid LA',
  'Amibid LA Oral',
  'Amicar',
  'Amicar Intravenous',
  'Amidate',
  'Amifampridine',
  'Amifostine',
  'Amifostine Intravenous',
  'Amigesic',
  'Amikacin',
  'Amikacin Injection',
  'Amikacin liposome',
  'Amikacin liposome Inhalation',
  'Amikin',
  'Amikin Pediatric',
  'Amiloride',
  'Amiloride and hydrochlorothiazide',
  'Amino acids and electrolytes in dextrose with calcium Intravenous',
  'Amino acids in dextrose Intravenous',
  'Amino Acids Injection',
  'Amino acids Intravenous',
  'Amino-CR',
  'Aminobenzoate potassium',
  'Aminocaproic',
  'Aminocaproic acid',
  'Aminocaproic Acid Injection',
  'Aminocaproic acid Intravenous',
  'Aminocaproic Acid Oral Solution',
  'Aminofen',
  'Aminohippurate sodium Intravenous',
  'Aminolevulinic acid',
  'Aminolevulinic acid topical',
  'Aminomine',
  'Aminophylline',
  'Aminophylline injection',
  'Aminophylline Intravenous',
  'Aminophylline Oral Solution',
  'Aminophylline Tablets',
  'Aminosalicylate sodium',
  'Aminosalicylic Acid',
  'Aminosyn',
  'Aminosyn 10%',
  'Aminosyn II Injection',
  'Aminosyn II Sulfite Free',
  'Aminosyn-PF Injection',
  'Aminoxin',
  'Amiodarone',
  'Amiodarone injection',
  'Amiodarone Intravenous',
  'Amiodarone Intravenous, Oral',
  'Amisulpride',
  'Amisulpride Intravenous',
  'Amitiza',
  'Amitriptyline',
  'Amitriptyline and chlordiazepoxide',
  'Amitriptyline and perphenazine',
  'Amivantamab',
  'Amivantamab-vmjw',
  'Amivantamab-vmjw Intravenous',
  'Amjevita',
  'Amjevita Subcutaneous',
  'Amlactin',
  'Amlexanox Mucous membrane, oral',
  'Amlodipine',
  'Amlodipine and atorvastatin',
  'Amlodipine and Atorvastatin Tablets',
  'Amlodipine and benazepril',
  'Amlodipine and celecoxib',
  'Amlodipine and olmesartan',
  'Amlodipine and Olmesartan Medoxomil',
  'Amlodipine and perindopril',
  'Amlodipine and telmisartan',
  'Amlodipine and valsartan',
  'Amlodipine, hydrochlorothiazide, and olmesartan',
  'Amlodipine, hydrochlorothiazide, and valsartan',
  'Amlodipine, valsartan, and hydrochlorothiazide',
  'Ammens Medicated Topical application',
  'Ammonia Inhalants',
  'Ammonia N-13',
  'Ammoniated mercury Topical',
  'Ammonium Chloride',
  'Ammonium Lactate',
  'Ammonium lactate and urea topical',
  'Ammonium Lactate Cream',
  'Ammonium lactate topical',
  'Ammonium molybdate Intravenous, Injection',
  'Ammonul',
  'Amnesteem',
  'Amoclan',
  'Amondys 45',
  'Amoxapine',
  'Amoxicillin',
  'Amoxicillin and Clavulanate',
  'Amoxicillin and Clavulanate Chewable',
  'Amoxicillin and Clavulanate ER Tablets',
  'Amoxicillin and Clavulanate Oral Suspension',
  'Amoxicillin and clavulanate potassium',
  'Amoxicillin and Clavulanate Tablets',
  'Amoxicillin and vonoprazan',
  'Amoxicillin Capsules',
  'Amoxicillin Chewable',
  'Amoxicillin Extended Release Tablets',
  'Amoxicillin Suspension',
  'Amoxicillin Tablets',
  'Amoxicillin, clarithromycin, and lansoprazole',
  'Amoxicillin, clarithromycin, and omeprazole',
  'Amoxicillin, clarithromycin, and vonoprazan',
  'Amoxicillin, omeprazole, and rifabutin',
  'Amoxicot',
  'Amoxil',
  'Amoxil Oral',
  'Amoxil Pediatric',
  'Amoxil Pediatric Oral',
  'Amphadase',
  'Amphadase injection',
  'Amphenol-40',
  'Amphetamine',
  'Amphetamine and dextroamphetamine',
  'Amphetamine Suspension',
  'Amphetamine Tablets',
  'Amphocin',
  'Amphojel',
  'Amphotec',
  'Amphotericin B',
  'Amphotericin b cholesteryl sulfate complex Intravenous',
  'Amphotericin b Intravenous, Injection',
  'Amphotericin B lipid complex',
  'Amphotericin b lipid complex Intravenous, Injection',
  'Amphotericin B liposomal',
  'Amphotericin b liposome Intravenous',
  'Ampicillin',
  'Ampicillin and sulbactam',
  'Ampicillin and sulbactam Injection',
  'Ampicillin Capsules',
  'Ampicillin injection',
  'Ampicillin Sodium',
  'Ampyra',
  'Amrix',
  'Amsacrine Intravenous',
  'Amturnide',
  'Amvuttra',
  'Amyl Nitrite Inhalant',
  'Amyl nitrite Inhalation, oral/nebulization',
  'Amytal Sodium',
  'Amyvid',
  'Amyvid Injection',
  'Amzeeq',
  'An-DTPA',
  'Ana-Lex Cream',
  'Ana-Lex topical/rectal',
  'Anabolic steroid Oral, Parenteral',
  'Anacaine',
  'Anacaulase',
  'Anacaulase-bcdb Topical application',
  'Anacin',
  'Anacin Advanced Headache Formula',
  'Anacin AF',
  'Anacin Aspirin Free',
  'Anadrol',
  'Anafranil',
  'Anagrelide',
  'Anakinra',
  'Anakinra Subcutaneous',
  'Analgesic Balm',
  'Analgesic combination, acetaminophen/salicylate',
  'Analpram HC Cream',
  'AnaMantle HC',
  'Anaplex DM',
  'Anaprox',
  'Anaprox-DS',
  'Anascorp',
  'Anascorp Injection',
  'Anasept',
  'Anasept Cleanser',
  'Anaspaz',
  'Anastrozole',
  'Anavip',
  'Anbesol',
  'Anbesol Extra Strength',
  'Anbesol Gel',
  'Anbesol Liquid',
  'Ancef',
  'Ancobon',
  'Andehist DM NR Syrup',
  'Andexxa',
  'Andrachne',
  'Andriol',
  'Androderm',
  'AndroGel',
  'AndroGel Packets',
  'AndroGel Pump 1.25 g/actuation',
  'Androgen Oral, Parenteral, Subcutaneous, Topical application, Transdermal',
  'Andrographis',
  'Android',
  'Androplex',
  'Androxy',
  'AneCream',
  'Anectine',
  'Anestacon Topical application',
  'Anesthesia S/I-40',
  'Anesthesia S/I-50',
  'Anesthetic Gel',
  'Anesthetic, general Inhalation, Parenteral, Rectal',
  'Anesthetic, local Parenteral',
  'Anesthetic, local Rectal',
  'Anesthetic, local Topical application',
  'Anesthetic, local Topical application, dental, Buccal mucosa, Gargle',
  'Anexsia',
  'Angelica',
  'Angeliq',
  'Angiomax',
  'Angioscein',
  'Angiotensin II',
  'Angiotensin ii Intravenous',
  'Anidulafungin',
  'Anidulafungin Intravenous',
  'Anifrolumab',
  'Anifrolumab-fnia Intravenous',
  'Animal Allergens Injection',
  'Animi-3',
  'Anise',
  'Anjeso',
  'Annovera',
  'Annovera Ring',
  'Anodyne LPT',
  'Anolor 300',
  'Anolor 300 Oral',
  'Anorectal Cream',
  'Anoro Ellipta',
  'Ansaid',
  'Ansuvimab-zykl',
  'Ansuvimab-zykl Intravenous',
  'Antabuse',
  'Antacid',
  'Antacids',
  'Antagon',
  'Antara',
  'Anthim',
  'Anthraforte 2% Topical',
  'Anthraforte 3% Topical',
  'Anthralin Topical',
  'Anthrascalp Topical',
  'Anthrasil',
  'Anthrax immune globulin Intravenous',
  'Anthrax Immune Globulin IV (Human)',
  'Anthrax vaccine',
  'Anthrax vaccine Intramuscular',
  'Anti-Diarrheal Tablet',
  'Anti-Fungal Liquid',
  'Anti-Gas Ultra Strength',
  'Anti-inflammatory drugs, nonsteroidal Ophthalmic',
  'Anti-inhibitor coagulant complex',
  'Anti-inhibitor coagulant complex Intravenous',
  'Anti-Itch Steroid Free',
  'Anti-thymocyte globulin rabbit',
  'Antibiotic Cream Topical',
  'Antibiotic Otic',
  'Anticholinergics and antispasmodics Oral, Parenteral, Rectal, Transdermal',
  'Anticoagulant Citrate Dextrose A',
  'Anticoagulant Citrate Phosphate Dextrose Adenine Solution',
  'Anticoagulant Citrate Phosphate Double Dextrose Solution',
  'Antiflex',
  'Antifungal, azole Vaginal',
  'Antiglaucoma agent, cholinergic, long-acting Ophthalmic',
  'Antihemophilic and von Willebrand factor complex',
  'Antihemophilic factor (recombinant) pegylated-aucl Intravenous',
  'Antihemophilic factor (recombinant) porcine sequence Intravenous',
  'Antihemophilic Factor (recombinant), Fc Fusion Protein',
  'Antihemophilic factor (recombinant), fc-vwf-xten fusion protein-ehtl Intravenous',
  'Antihemophilic Factor (recombinant), Glycopegylated-exei',
  'Antihemophilic factor (recombinant), glycopegylated-exei Intravenous',
  'Antihemophilic Factor (recombinant), PEGylated',
  'Antihemophilic Factor (recombinant), PEGylated-aucl',
  'Antihemophilic Factor (Recombinant), Porcine Sequence',
  'Antihemophilic factor human',
  'Antihemophilic factor Intravenous, Injection',
  'Antihemophilic factor recombinant',
  'Antihemophilic factor viii and von willebrand factor Intravenous',
  'Antihistamine Oral, Parenteral, Rectal',
  'Antihistamine, decongestant, and analgesic combination',
  'Antihistamine, decongestant, and anticholinergic combination',
  'Antihistamine/decongestant combination',
  'Antilirium',
  'Antimyasthenic Oral, Parenteral',
  'Antinaus 50',
  'Antipyrine and Benzocaine Ear Drops',
  'Antipyrine and benzocaine Otic',
  'Antispasmodic',
  'Antithrombin alfa',
  'Antithrombin III',
  'Antithymocyte Globulin (Equine)',
  'Antithymocyte globulin rabbit Intravenous',
  'Antithyroid agent Oral, Rectal',
  'Antitussin',
  'Antivenin',
  'Antivenin (Crotalidae) polyvalent',
  'Antivenin (crotalidae) polyvalent immune fab Intravenous',
  'Antivenin (crotalidae) polyvalent Injection',
  'Antivenin (Latrodectus mactans) (Equine)',
  'Antivenin (latrodectus mactans) Injection',
  'Antivenin (micrurus fulvius) Intravenous',
  'Antivenin Black Widow Spider',
  'Antivenin Injection',
  'Antivenin North American Coral Snake',
  'Antivenin Polyvalent',
  'Antivenin-Spider',
  'Antivenom Centruroides scorpion',
  'Antivert',
  'Antivert/25',
  'Antivert/50',
  'Antizol',
  'Anturol',
  'Anu-Med rectal',
  'Anucort-HC cream, suppository',
  'Anucort-HC Suppository',
  'Anusol HC',
  'Anusol HC Suppository',
  'Anusol-HC cream, suppository',
  'Anzemet',
  'Anzemet Oral',
  'Aortic Extract',
  'A-Phedrin',
  'Apadaz',
  'Apalutamide',
  'APAP w/Codeine',
  'ApexiCon',
  'ApexiCon E',
  'APF Gel',
  'Aphedrid',
  'Aphthasol',
  'Apidra',
  'Apixaban',
  'Aplenzin',
  'Aplicare One Hydrogen Peroxide',
  'Aplicare One Tincture Of Iodine Topical',
  'Aplicare Povidone Iodine Scrub',
  'Aplisol',
  'Apo-Amoxi',
  'Apo-Amoxi Clav',
  'Apo-Amoxi Oral',
  'Apo-Amoxi Sugar-Free',
  'Apo-Amoxi Sugar-Free Oral',
  'APO-Amphetamine XR - 10MG Tablet',
  'APO-Amphetamine XR - 15MG Tablet',
  'APO-Amphetamine XR - 20MG Tablet',
  'APO-Amphetamine XR - 25MG Tablet',
  'APO-Amphetamine XR - 30MG Tablet',
  'APO-Amphetamine XR - 5MG Tablet',
  'APO-ARIPiprazole',
  'APO-carBAMazepine',
  'APO-carBAMazepine CR',
  'APO-clonazePAM',
  'Apo-Cyclosporine Oral',
  'APO-fentaYNL Matrix',
  'Apo-Gain Topical',
  'Apo-Haloperidol',
  'Apo-Ipravent',
  'Apo-Isdn',
  'Apo-Ketorolac',
  'APO-metFORMIN',
  'APO-metFORMIN ER',
  'APO-Nabilone',
  'APO-Nifed',
  'APO-Nifed PA',
  'Apo-Pen-Vk',
  'APO-predniSONE',
  'APO-risperiDONE',
  'Apo-Salvent',
  'Apo-Salvent Inhaler',
  'Apo-Sulfatrim',
  'Apo-Tobramycin',
  'APO-traMADol/ACET',
  'Apokyn',
  'Apomorphine',
  'Apomorphine Injection',
  'Apomorphine Subcutaneous',
  'Apomorphine Sublingual',
  'Aponvie',
  'Appearex',
  'Apple Cider Vinegar',
  'Apples',
  'Apra',
  'Apraclonidine',
  'Apraclonidine ophthalmic',
  'Apremilast',
  'Aprepitant',
  'Aprepitant Intravenous',
  'Aprepitant/Fosaprepitant',
  'Apresazide',
  'Apresoline',
  'Apresoline Injection',
  'Apretude',
  'Apri',
  'Apricot',
  'Apriso',
  'Aprizio Pak',
  'Aprodine',
  'Aptensio XR',
  'Aptiom',
  'Aptivus',
  'Aqua Care',
  'Aqua Gem-E',
  'Aqua-Ban',
  'Aquafresh',
  'Aquamephyton',
  'Aquanil HC',
  'Aquaphilic with Urea',
  'Aquaphor Healing',
  'Aquasol A',
  'Aquasol E',
  'Aquatab D',
  'Aquatab DM',
  'Aquatensen',
  'Aquax-H Cream',
  'Aquazide H',
  'Aquoral',
  'Arabinoxylan',
  'Arakoda',
  'Aralast',
  'Aralast NP',
  'Aralen',
  'Aralen Phosphate',
  'Aranelle',
  'Aranesp',
  'Arava',
  'Arazlo',
  'Arazlo Topical',
  'Arbinoxa',
  'Arcalyst',
  'Arcapta',
  'Arcapta Neohaler',
  'Arcoxia',
  'Arctic Relief',
  'Ardeparin Subcutaneous',
  'Aredia',
  'Arestin',
  'Arestin mucous membrane powder',
  'Arformoterol',
  'Arformoterol inhalation',
  'Arformoterol Inhalation Solution',
  'Argania',
  'Argatroban',
  'Argatroban Intravenous',
  'Arginine',
  'Arginine Intravenous',
  'Aricept',
  'Aricept ODT',
  'Aricept Oral Solution',
  'Aricept Tablets',
  'Aridol',
  'Aridol Bronchial Challenge Test Kit',
  'Arikayce',
  'Arimidex',
  'Aripiprazole',
  'Aripiprazole injection',
  'Aripiprazole Intramuscular',
  'Aripiprazole lauroxil Intramuscular',
  'Aripiprazole ODT',
  'Aripiprazole Oral Solution',
  'Aripiprazole oral with sensor',
  'Aripiprazole Tablets',
  'Aristada',
  'Aristada Initio',
  'Aristada injection',
  'Aristocort',
  'Aristocort A',
  'Aristocort C Concentrate',
  'Aristocort D Dilute',
  'Aristocort Forte',
  'Aristocort R Ointment Regular',
  'Aristocort R Regular',
  'Aristospan',
  'Arixtra',
  'Armodafinil',
  'ArmonAir Digihaler',
  'Armonair Digihaler with eModule',
  'Armonair Respiclick',
  'Armour Thyroid',
  'Arnica',
  'Arnuity Ellipta',
  'Aromasin',
  'Aromatic ammonia spirit Inhalation, oral/nebulization',
  'Arranon',
  'Arrestin',
  'Arsenic trioxide',
  'Arsenic Trioxide Injection',
  'Arsenic trioxide Intravenous',
  'Artane',
  'Artelac Nighttime',
  'Artemether and lumefantrine',
  'Artesunate',
  'Artesunate Injection',
  'Artesunate Intravenous',
  'Arthricare For Women Topical',
  'Arthriten',
  'Arthritis Pain',
  'Arthritis Pain Relief',
  'Arthrotec',
  'Articadent',
  'Articadent Dental with Ephinephrine',
  'Articaine',
  'Articaine and epinephrine',
  'Articaine and epinephrine Injection',
  'Artichoke',
  'Artificial Tears',
  'Artiss',
  'Artiss Duo Set',
  'Artiss Duploject',
  'Artiss Frozen',
  'Arymo ER',
  'Arze-Ject-A',
  'Arzerra',
  'Asacol',
  'Asacol 800',
  'Asacol 800 Oral, Rectal',
  'Asacol HD',
  'Asafoetida',
  'Ascarel',
  'Asceniv',
  'Asceniv Intramuscular, Intravenous, Subcutaneous',
  'Asceniv Intravenous',
  'Asciminib',
  'Asclera',
  'Asclera Injection',
  'Ascocid',
  'Ascomp w/Codeine',
  'Ascomp with Codeine',
  'Ascor',
  'Ascor Injection',
  'Ascorbic acid',
  'Ascorbic acid and carbonyl iron',
  'Ascorbic Acid Injection',
  'Ascorbic acid Intravenous',
  'Ascorbic Acid Quick Melts',
  'Ascriptin',
  'Asenapine',
  'Asenapine sublingual',
  'Asenapine Tablets',
  'Asenapine transdermal',
  'Asendin',
  'Asfotase alfa',
  'Asfotase alfa Subcutaneous',
  'Ashlyna',
  'Ashwagandha',
  'Asmanex',
  'Asmanex HFA',
  'Asmanex Twist',
  'Asmanex Twisthaler',
  'Asmanex Twisthaler 120 Dose',
  'Asmanex Twisthaler 60 Dose',
  'Asparaginase (Erwinia chrysanthemi) (recombinant)-rywn',
  'Asparaginase Erwinia chrysanthemi',
  'Asparaginase erwinia chrysanthemi Intramuscular',
  'Asparaginase erwinia chrysanthemi recombinant-rywn Intramuscular',
  'Asparagus',
  'Asparlas',
  'Aspercreme Heat Pain Relieving',
  'Aspergum',
  'Aspi-Cor',
  'Aspir-Low',
  'Aspirin',
  'Aspirin and caffeine',
  'Aspirin and dipyridamole',
  'Aspirin and Dipyridamole Capsules',
  'Aspirin and omeprazole',
  'Aspirin and Omeprazole Tablets',
  'Aspirin Low Dose Enteric Coated',
  'Aspirin rectal',
  'Aspirin, butalbital, and caffeine',
  'Aspirin, butalbital, caffeine, and codeine',
  'Aspirin, caffeine, and dihydrocodeine',
  'Aspirin, caffeine, and orphenadrine',
  'Aspirin, carisoprodol, and codeine',
  'Aspirin, chlorpheniramine, and phenylephrine',
  'Aspirin, sodium bicarbonate, and citric acid',
  'Aspirtab',
  'Aspruzyo Sprinkle',
  'Assure Sore Throat',
  'Astagraf XL',
  'Astelin',
  'Astelin Ready-Spray',
  'Astepro',
  'Astepro Allergy',
  'Astero Gel',
  'Asthmanefrin',
  'Astragalus',
  'Astramorph PF',
  'AstrinGyn',
  'Atacand',
  'Atacand HCT',
  'Atarax',
  'Atazanavir',
  'Atazanavir and cobicistat',
  'Atelvia',
  'Atenolol',
  'Atenolol and chlorthalidone',
  'Atenolol and Chlorthalidone Tablets',
  'Atenolol Tablets',
  'Atezolizumab',
  'Atgam',
  'Atgam equine',
  'Athlete\'s Foot Cream',
  'Ativan',
  'Ativan injection',
  'Ativan Tablets',
  'ATNAA',
  'Atogepant',
  'Atoltivimab, Maftivimab, and Odesivimab-ebgn',
  'Atomoxetine',
  'Atopica',
  'Atorvaliq',
  'Atorvastatin',
  'Atovaquone',
  'Atovaquone and proguanil',
  'Atovaquone Suspension',
  'Atrac-Tain',
  'Atracurium',
  'Atracurium Besylate Injection',
  'Atralin',
  'Atralin Gel',
  'Atridox',
  'Atripla',
  'AtroPen',
  'AtroPen Auto-Injector injection',
  'Atropine',
  'Atropine (EENT)',
  'Atropine and diphenoxylate',
  'Atropine and pralidoxime',
  'Atropine injection',
  'Atropine ophthalmic',
  'Atropine Ophthalmic Solution',
  'Atropine Sulfate Ophthalmic Ointment',
  'Atropine, hyoscyamine, methenamine, methylene blue, phenyl salicylate, and benzoic acid',
  'Atropine-1',
  'Atrovent HFA',
  'Atrovent Nasal',
  'Atrovent Nasal Spray',
  'ATryn',
  'Aubagio',
  'Aubra',
  'Aubra EQ',
  'Audenz',
  'Augmentin',
  'Augmentin Chewable',
  'Augmentin ES-600',
  'Augmentin Oral Suspension',
  'Augmentin XR',
  'Auranofin',
  'Auraphene-B otic',
  'Aureo S 700',
  'Aureomycin',
  'AURO-ARIPiprazole',
  'Auro-Dri',
  'AURO-metFORMIN',
  'Auro-traMADol/Acetaminophen',
  'Aurodex',
  'Aurodex Ear Drops',
  'Aurophen',
  'Auroto',
  'Aurovela 1.5/30',
  'Aurovela 1/20',
  'Aurovela 24 Fe',
  'Aurovela Fe 1.5/30',
  'Aurovela Fe 1/20',
  'Auryxia',
  'Auryxia Oral, Parenteral',
  'Austedo',
  'Autoplex T',
  'Autumn Crocus',
  'Auvelity',
  'Auvi-QAVA-metFORMIN',
  'Avaclyr',
  'Avacopan',
  'Avage',
  'Avage Topical',
  'Avalglucosidase alfa',
  'Avalglucosidase alfa-ngpt Intravenous',
  'Avalide',
  'Avanafil',
  'Avandamet',
  'Avandaryl',
  'Avandia',
  'Avant Oral Rinse',
  'Avant Original Fragrance Free',
  'Avapritinib',
  'Avapro',
  'Avar Cleanser',
  'Avar LS Cleanser Emulsion',
  'Avar-E Cream',
  'Avar-E Green Cream',
  'Avar-E LS Cream',
  'Avastin',
  'Avatrombopag',
  'AVC',
  'Avedana Medicated Chest Rub',
  'Avedana Pain Relieving Roll On',
  'Aveed',
  'Avelox',
  'Avelox I.V.',
  'Avelox Injection',
  'Avelox oral/injection',
  'Avelumab',
  'Avelumab Intravenous',
  'Aventyl',
  'Aviane',
  'Aviane 28',
  'Avibactam and cefTAZidime',
  'Avinza',
  'Avita',
  'Avita Cream',
  'Avita Topical',
  'Avocado',
  'Avocado/Soybean Unsaponifiables',
  'Avodart',
  'Avonex',
  'Avonex Pen',
  'Avosil Topical',
  'Avsola',
  'AVSOLA Intravenous',
  'Avycaz',
  'Axert',
  'Axicabtagene ciloleucel',
  'Axicabtagene ciloleucel Intravenous',
  'Axid',
  'Axid AR',
  'Axid Pulvules',
  'Axiron',
  'Axitinib',
  'Axumin',
  'Aygestin',
  'Aygestin Oral, Implantation, Parenteral',
  'Aygestin Oral, Parenteral, Vaginal',
  'Ayr Saline nasal',
  'Ayr Sinus Rinse Kit nasal',
  'Ayuna',
  'Ayvakit',
  'Azacitidine',
  'Azacitidine Injection',
  'Azacitidine Subcutaneous',
  'Azactam',
  'Azactam injection',
  'Azasan',
  'AzaSite',
  'Azathioprine',
  'Azathioprine Injection',
  'Azathioprine Intravenous',
  'Azathioprine Oral, Intravenous',
  'Azedra',
  'Azedra Injection',
  'Azelaic Acid',
  'Azelaic Acid Gel',
  'Azelaic acid topical',
  'Azelastine',
  'Azelastine and fluticasone nasal',
  'Azelastine and Fluticasone Nasal Spray',
  'Azelastine nasal',
  'Azelastine ophthalmic',
  'Azelastine Ophthalmic Solution',
  'Azelex',
  'Azelex Topical',
  'Azficel-t Intradermal',
  'Azilect',
  'Azilsartan',
  'Azilsartan and chlorthalidone',
  'Azithromycin',
  'Azithromycin 3 Day Dose Pack',
  'Azithromycin 5 Day Dose Pack',
  'Azithromycin Dihydrate',
  'Azithromycin Injection',
  'Azithromycin Intravenous',
  'Azithromycin ophthalmic',
  'Azithromycin Oral Suspension',
  'Azithromycin Tablets',
  'Azmacort',
  'Azmax Twisthaler',
  'AZO Cranberry Gummies',
  'AZO Urinary Pain Relief',
  'AZO Urinary Tract Health',
  'Azo-Cranberry',
  'Azo-Gesic',
  'Azo-Septic',
  'Azo-Standard',
  'Azolen',
  'Azopt',
  'Azopt 1%',
  'Azor',
  'Azstarys',
  'Aztreonam',
  'Aztreonam inhalation',
  'Aztreonam injectio',
  'Aztreonam Intravenous, Injection',
  'Azulfidine',
  'Azulfidine EN Tablets',
  'Azulfidine EN-tabs',
  'Azulfidine Entabs Oral, Rectal',
  'Azulfidine Oral, Rectal',
  'Azuphen MB',
  'Azurette',
  'Cabazitaxel',
  'Cabazitaxel Intravenous',
  'Cabenuva',
  'Cabergoline',
  'Cablivi',
  'Cabometyx',
  'Cabotegravir',
  'Cabotegravir and rilpivirine',
  'Cabotegravir and rilpivirine Intramuscular',
  'Cabotegravir Intramuscular',
  'Cabozantinib',
  'Caduet',
  'Cafcit',
  'Cafcit injection/oral liquid',
  'Cafcit Intravenous',
  'Cafcit Oral',
  'Cafergot',
  'Cafergot Oral',
  'Cafergot Rectal',
  'Cafergot Tablets',
  'Caffeine',
  'Caffeine and ergotamine oral/rectal',
  'Caffeine and sodium benzoate Injection',
  'Caffeine Citrate',
  'Caffeine citrate injection/oral liquid',
  'Caffeine citrate Intravenous',
  'Caffeine/Caffeine and Sodium Benzoate',
  'Calabar Bean',
  'Calaclear',
  'Caladryl Clear',
  'Calamine Lotion Topical',
  'Calamine Plain topical',
  'Calamine topical',
  'Calamus',
  'Calan',
  'Calan SR',
  'Calanolide A',
  'Calaspargase pegol',
  'Calaspargase Pegol-mknl',
  'Calaspargase pegol-mknl Intravenous',
  'Calcibind',
  'Calcidol',
  'Calcifediol',
  'Calciferol',
  'Calciferol Oral',
  'Calcipotriene',
  'Calcipotriene and Betamethasone Ointment',
  'Calcipotriene and Betamethasone Topical Suspension',
  'Calcipotriene Cream',
  'Calcipotriene Foam',
  'Calcipotriene Ointment',
  'Calcipotriene Scalp Solution',
  'Calcipotriene topical',
  'Calcitonin',
  'Calcitonin injection',
  'Calcitonin nasal',
  'Calcitonin-Salmon Injection',
  'Calcitonin-Salmon Nasal Spray',
  'Calcitrate with D',
  'Calcitrene',
  'Calcitrene Topical',
  'Calcitriol',
  'Calcitriol Capsules',
  'Calcitriol Injection',
  'Calcitriol Ointment',
  'Calcitriol topical',
  'Calcitriol Topical application',
  'Calcium acetate',
  'Calcium Acetate Capsules',
  'Calcium Acetate Gelcaps',
  'Calcium Acetate Tablets',
  'Calcium and vitamin D combination',
  'Calcium carbonate',
  'Calcium carbonate and magnesium chloride',
  'Calcium carbonate and magnesium hydroxide',
  'Calcium carbonate, famotidine, and magnesium hydroxide',
  'Calcium carbonate, magnesium hydroxide, and simethicone',
  'Calcium chloride/dextrose/hetastarch/magnesium chloride/potassium chloride/sodium chloride/sodium lactate Intravenous',
  'Calcium citrate',
  'Calcium Disodium Versenate',
  'Calcium Folinate Injection',
  'Calcium Gluconate',
  'Calcium Gluconate Injection',
  'Calcium lactate',
  'Calcium oxybate, magnesium oxybate, potassium oxybate, and sodium oxybate',
  'Calcium phosphate, tribasic',
  'Calcium Salts',
  'Calcium supplement Oral, Parenteral',
  'Calcium, magnesium, potassium, and sodium oxybates',
  'Calcium-Folic Acid Plus D',
  'Caldecort',
  'Caldesene Topical',
  'Caldolor',
  'Caldyphen Clear',
  'Calendula',
  'Calfactant',
  'Calgon Vesta',
  'Callergy Clear',
  'Calmoseptine',
  'Calomist',
  'Calphron',
  'Calquence',
  'Calquence Tablets',
  'Caltrate 600+D Soft Chews',
  'Cambia',
  'Camcevi',
  'Camila',
  'Camila Oral, Implantation, Parenteral',
  'Camila Oral, Parenteral, Vaginal',
  'Campath',
  'Camphor and menthol topical',
  'Camphor, eucalyptus, and menthol topical',
  'Camphor, lidocaine, and methyl salicylate topical',
  'Camphor, menthol, and methyl salicylate topical',
  'Campral',
  'Camptosar',
  'Camrese',
  'Camrese extended-cycle',
  'Camrese Lo extended-cycle',
  'CamreseLo',
  'Camzyos',
  'Canagliflozin',
  'Canagliflozin and metformin',
  'Canakinumab',
  'Canakinumab Subcutaneous',
  'Canasa',
  'Canasa Oral, Rectal',
  'Canasa Pac rectal',
  'Canasa Rectal',
  'Cancidas',
  'Candesartan',
  'Candesartan and hydrochlorothiazide',
  'Candesartan and Hydrochlorothiazide Tablets',
  'Candin',
  'CanesOral',
  'Canesten Topical',
  'Canges-HC',
  'Canges-XP',
  'Cangrelor',
  'Cangrelor Intravenous',
  'Cannabidiol',
  'Cantil',
  'Capastat Sulfate',
  'Capecitabine',
  'Capers',
  'Capex',
  'Capex Shampoo',
  'Caphosol',
  'Capital w/Codeine',
  'Capitrol Topical',
  'Caplacizumab',
  'Caplacizumab-yhdp',
  'Caplacizumab-yhdp Intravenous, Subcutaneous',
  'Caplyta',
  'Capmatinib',
  'Capmist DM',
  'Capoten',
  'Capozide 25/15',
  'Capozide 25/25',
  'Capozide 50/15',
  'Capozide 50/25',
  'Caprelsa',
  'Capreomycin',
  'Capreomycin Injection',
  'Capron DM',
  'Capron DMT',
  'Caprylic Acid',
  'Caprylidene',
  'Capsagel Topical',
  'Capsagesic-HP Arthritis Relief Topical',
  'CAPSAICIN',
  'Capsaicin and diclofenac topical',
  'Capsaicin topical',
  'Capsaicin, lidocaine, menthol, and methyl salicylate topical',
  'Capsfenac Pak',
  'Capsicum Peppers',
  'Capsin',
  'Capsin Topical',
  'Capsinac',
  'Capstar',
  'Captique',
  'Captopril',
  'Captopril and hydrochlorothiazide',
  'Captopril and Hydrochlorothiazide Tablet',
  'Captopril Tablets',
  'Capxib',
  'Capzasin-HP',
  'Carac',
  'Carac Topical',
  'Carafate',
  'Carafate Tablets',
  'Carb-O-Lac HP topical',
  'Carb-O-Lac5 topical',
  'Carb-O-Philic/10',
  'Carb-O-Sal5',
  'Carbachol',
  'Carbachol ophthalmic',
  'Carbaglu',
  'Carbamazepine',
  'Carbamazepine Capsules',
  'Carbamazepine Chewable',
  'Carbamazepine ER',
  'Carbamazepine Intravenous',
  'Carbamazepine Oral Suspension',
  'Carbamide Peroxide',
  'Carbamide peroxide otic',
  'Carbatrol',
  'Carbetapentane and chlorpheniramine',
  'Carbetapentane and guaifenesin',
  'Carbetocin Intravenous',
  'Carbidopa',
  'Carbidopa and levodopa',
  'Carbidopa and levodopa enteral',
  'Carbidopa and Levodopa ODT',
  'Carbidopa and Levodopa Tablets',
  'Carbidopa Tablets',
  'Carbidopa, entacapone, and levodopa',
  'Carbidopa, Levodopa and Entacapone Tablets',
  'Carbihist',
  'Carbinoxamine',
  'Carbocaine',
  'Carbocaine HCl',
  'Carbocaine Injection',
  'Carbocaine with Neo-Cobefrin',
  'Carbogen',
  'Carbohydrate and electrolyte combination',
  'Carbol-fuchsin solution Topical',
  'Carbon Dioxide',
  'Carbon Dioxide Air Mixture',
  'Carbon Dioxide Nitrogen Mix',
  'Carbon Dioxide Oxygen Mixture',
  'Carbon Dioxide Refrigerated Gas',
  'Carbon Dioxide Refrigerated Liquid',
  'Carbon Dioxide-Oxygen-Nitrogen Mixture',
  'Carbonic anhydrase inhibitor Oral, Parenteral',
  'Carbonyl iron',
  'Carboplatin',
  'Carboplatin Intravenous',
  'Carboprost',
  'Carboprost Injection',
  'Carboprost Intramuscular',
  'Carboxine',
  'Cardene',
  'Cardene Injection',
  'Cardene Intravenous',
  'Cardene IV',
  'Cardene SR',
  'Cardiogen-82',
  'Cardiogen-82 Generator',
  'Cardiolite',
  'Cardioplegic',
  'Cardioquin',
  'Cardioxane Injection',
  'Cardizem',
  'Cardizem CD',
  'Cardizem Intravenous',
  'Cardizem LA',
  'Cardura',
  'Cardura XL',
  'CareOne Clearlax',
  'Careone Hair Regrowth Treatment for Men',
  'Carfilzomib',
  'Carfilzomib Intravenous',
  'Carglumic acid',
  'Carglumic Acid Tablets',
  'Carimune',
  'Carimune IGIV',
  'Carimune NF',
  'Cariprazine',
  'Carisoprodol',
  'Carisoprodol and aspirin',
  'Carisoprodol, aspirin, and codeine',
  'Carlson D',
  'Carmol',
  'Carmustine',
  'Carmustine Implantation',
  'Carmustine Injection',
  'Carmustine injection/implant',
  'Carmustine Intravenous',
  'Carnexiv',
  'Carnitine',
  'Carnitor',
  'Carnitor Injection',
  'Carnitor Oral Solution',
  'Carnitor Sugar-Free Solution',
  'Carnitor Tablets',
  'CaroSpir',
  'Carospir Suspension',
  'Carprofen',
  'Carrington Antifungal Topical',
  'Carrot Oil',
  'Carteolol',
  'Carteolol ophthalmic',
  'Cartia XT',
  'Carticel',
  'Carvedilol',
  'Carvedilol Capsule',
  'Carvykti',
  'Cascara',
  'Casimersen',
  'Casimersen Intravenous',
  'Casirivimab',
  'Casirivimab and imdevimab',
  'Casodex',
  'Caspofungin',
  'Caspofungin Acetate Injection',
  'Caspofungin Intravenous',
  'Casporyn HC',
  'Casporyn HC Ear Drops',
  'Cassipa',
  'Castellani Paint',
  'Castiva Cooling',
  'Castiva Warming',
  'Castor',
  'Castor Oil',
  'Cat Hair Standardized',
  'Cat Pelt Standardized',
  'Cat\'s claw',
  'Cataflam',
  'Catapres',
  'Catapres-TTS',
  'Catapres-TTS-1 Transdermal',
  'Catapres-TTS-2 Transdermal',
  'Catapres-TTS-3 Transdermal',
  'Cathflo Activase',
  'Catnip',
  'Catosal',
  'Caucasian Whortleberry',
  'Caverject',
  'CaverJect Impulse',
  'CaviRinse',
  'Cayston',
  'Caziant',
  'Babee Cof',
  'Babee Cof Syrup',
  'Babee Teething',
  'Baby Anbesol',
  'Baby Gasz',
  'Baby Orajel',
  'Baby Orajel Liquid',
  'Baby Orajel Nighttime Formula',
  'Baby Orajel Teething Medicine',
  'BabyBIG',
  'Baci-IM injection',
  'Bacid (LAC)',
  'Baciguent',
  'Baciguent Ophthalmic Ointment',
  'Bacillus Clausii',
  'Bacillus coagulans and inulin',
  'Bacillus of calmette and guerin vaccine, live Intradermal',
  'Bacillus of calmette and guerin vaccine, live Intravesical',
  'Bacitracin',
  'Bacitracin (EENT)',
  'Bacitracin and polymyxin B ophthalmic',
  'Bacitracin and polymyxin B topical',
  'Bacitracin and polymyxin b Topical application',
  'Bacitracin injection',
  'Bacitracin ophthalmic',
  'Bacitracin Polymyxin B',
  'Bacitracin topical',
  'Bacitracin, hydrocortisone, neomycin, and polymyxin B ophthalmic',
  'Bacitracin, neomycin, and polymyxin B ophthalmic',
  'Bacitracin, neomycin, and polymyxin B topical',
  'Backaid IPF',
  'Baclofen',
  'Baclofen Injection',
  'Baclofen Intrathecal',
  'Baclofen Oral Solution',
  'Baclofen Suspension',
  'Bacmin',
  'Bacopa',
  'Bacteriostatic Sodium Chloride',
  'Bacteriostatic Water for Injection',
  'Bactine',
  'Bactocill',
  'Bactracillin G Injection',
  'Bactrim',
  'Bactrim DS',
  'Bactroban',
  'Bactroban Cream',
  'Bactroban Nasal',
  'Bactroban Nasal Ointment',
  'Bactroban Ointment',
  'Bactroban Topical',
  'Bafiertam',
  'Baical Skullcap',
  'BAL In Oil',
  'Balacet 325 Tablets',
  'Balamine DM',
  'Balanced Salt Solution',
  'Balanced Salt Solution intraocular',
  'Balcoltra',
  'Balmex',
  'Balminil',
  'Balminil Dm Children',
  'Balminil Dm Sugar-Free',
  'BCG intravesical',
  'BCG vaccine',
  'Bcg Vaccine Freeze Dried',
  'BD Lactinex',
  'BD PosiFlush SF flush',
  'Bebtelovimab',
  'Bebtelovimab Intravenous',
  'Bebulin',
  'Bebulin VH',
  'Becaplermin',
  'Becaplermin topical',
  'Beclomethasone (EENT)',
  'Beclomethasone (Systemic, Oral Inhalation)',
  'Beclomethasone inhalation',
  'Beclomethasone nasal',
  'Beclovent',
  'Beconase',
  'Beconase AQ',
  'Bedaquiline',
  'Bedoz',
  'Bedside Care',
  'Bee pollen',
  'Bee Venom',
  'Beef,Iron & Wine',
  'BeeGentle Gel',
  'Beetroot',
  'Bekyree',
  'Belantamab mafodotin',
  'Belantamab mafodotin-blmf Intravenous',
  'Belatacept',
  'Belatacept Intravenous',
  'Belbuca',
  'Beleodaq',
  'Beleodaq Injection',
  'Belimumab',
  'Belimumab Intravenous',
  'Belinostat',
  'Belinostat Intravenous',
  'Belladonna',
  'Belladonna alkaloids and phenobarbital',
  'Belladonna and opium rectal',
  'Belladonna and Opium Suppository',
  'Belladonna Tincture',
  'Belladonna/Phenobarbital',
  'Bellafill',
  'Belrapzo',
  'Belsomra',
  'Belumosudil',
  'Belviq',
  'Belviq XR',
  'Belzutifan',
  'Bempedoic acid',
  'Bempedoic acid and ezetimibe',
  'Benadryl',
  'Benadryl Allergy Plus Congestion',
  'Benadryl Allergy Sinus Headache',
  'Benadryl Allergy Ultratab',
  'Benadryl Injection',
  'Benadryl Itch Cooling Spray',
  'Benadryl Itch Stopping Cream',
  'Benadryl Itch Stopping Gel',
  'Benalg',
  'Benazepril',
  'Benazepril and hydrochlorothiazide',
  'Bendamustine',
  'Bendamustine Injection',
  'Bendamustine Intravenous',
  'Bendeka',
  'Bendroflumethiazide and nadolol',
  'BeneFIX',
  'Benefix Intravenous',
  'Benemid',
  'BENGAY Arthritis',
  'Bengay Original',
  'BENGAY Pain Relieving',
  'Bengay Ultra Strength topical',
  'Benicar',
  'Benicar HCT',
  'Benlysta',
  'Benoquin',
  'Benralizumab',
  'Benralizumab Subcutaneous',
  'Bensal HP',
  'Bensal HP OintmentBentiromide',
  'Bentoquatam Topical',
  'BentylBenylin E Extra Strength Chest Congestion',
  'Benylin Pediatric Formula',
  'Benylin-E',
  'Benz-O-StheticBenzac ACBenzac Topical',
  'BenzaclinBenzacot',
  'Benzagel TopicalBenzamycin',
  'Benzamycin Gel',
  'Benzamycin Pak Topical',
  'Benzashave Topical',
  'Benzedrex',
  'BenzEFoam Ultra Topical',
  'BenzeProBenzePrO Creamy Wash',
  'BenzePrO Foam',
  'BenzePrO Foaming Cloths',
  'BenzePrO Short Contact Foam',
  'Benzethonium chloride topical',
  'Benzhydrocodone and acetaminophen',
  'Benziq',
  'Benziq Topical',
  'BenznidazoleBenzo-Jel',
  'Benzocaine (EENT)',
  'Benzocaine Gel',
  'Benzocaine Oral, Oromucosal',
  'Benzocaine topical',
  'Benzocaine Topical application',
  'BenzodentBenzodent Cream',
  'BenzonatateBenzotic',
  'Benzoyl peroxide and clindamycin topical',
  'Benzoyl peroxide and clindamycin Topical application',
  'Benzoyl peroxide and erythromycin topical',
  'Benzoyl peroxide and hydrocortisone topical',
  'Benzoyl peroxide and salicylic acid topical',
  'Benzoyl peroxide and tretinoin topical',
  'Benzoyl Peroxi'
];
